version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    build:
      context: .
    container_name: django
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c 'python manage.py collectstatic --noinput \
            && python manage.py migrate \
            && waitress-serve --port=8000 eCom.wsgi:application'


  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - webapp
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume:
  media_volume: